### Site metadata ###

site_name: terraform Reference
site_description: 'terraform tutorial with examples'
site_url: https://rmechi.github.io

repo_url: https://github.com/rmechi/terraform
edit_uri: edit/master/docs/docs

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
use_directory_urls: false
extra_css: [style.css]
markdown_extensions:
  - toc:
      permalink: "#"


nav:
  - Home: index.md
  - Tutorial:
      - Arrays: terraform/arrays.md
      - Slices: terraform/slices.md
      - GoMaps: terraform/maps.md

